--
-- PostgreSQL database dump
--

-- Dumped from database version 14.12
-- Dumped by pg_dump version 14.12

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: apartment_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.apartment_info (
    price integer,
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    address character varying(255),
    area_of_apartment integer,
    count_of_sleep_places integer,
    floor_number integer,
    has_parking_lot boolean DEFAULT false,
    has_sea_view boolean DEFAULT false,
    has_wi_fi boolean DEFAULT false,
    short_description character varying(255),
    description text
);


ALTER TABLE public.apartment_info OWNER TO postgres;

--
-- Name: apartment_info_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.apartment_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apartment_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.images (
    id bigint NOT NULL,
    bytes oid,
    content_type character varying(255),
    is_preview_image boolean,
    name character varying(255),
    original_file_name character varying(255),
    size bigint,
    apartment_id bigint
);


ALTER TABLE public.images OWNER TO postgres;

--
-- Name: images_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.images_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.images_seq OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    active boolean,
    date_of_created timestamp(6) without time zone,
    email character varying(255),
    name character varying(255),
    password character varying(1000),
    phone_number character varying(255),
    roles character varying(255),
    username character varying(255),
    role character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: apartment_info; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.apartment_info (price, id, name, address, area_of_apartment, count_of_sleep_places, floor_number, has_parking_lot, has_sea_view, has_wi_fi, short_description, description) FROM stdin;
17000	2	Синяя двушка в центре	tntuyu str.65	25	2	12	t	t	t	Просторная светлая двухкомнатная квартира в светлых тонах в центре города Одессы. До главной достопримечательности - Дерибасовской улицы всего 5 минут!	Роскошная квартира с видом на море, расположена в новострое в самом сердце Одессы, в престижном районе Аркадия. Здесь вы найдете все для комфортного проживания: бесплатный Wi-Fi, собственное парковочное место и уютные современные интерьеры. Квартира идеально подходит для отдыха на побережье, ведь до пляжа всего несколько минут пешком. Вблизи расположены лучшие рестораны, ночные клубы и знаменитый Аркадиевский парк. Насладитесь прогулками по Приморскому бульвару, посетите Потемкинскую лестницу и знаменитый Одесский театр оперы и балета.
24000	3	Зеленая трешка на таирово	mutrfvs str.84	16	1	1	f	f	t	Прекрасная трехкомнатная квартира в салатовых тонах в замечательном тихом спально районе города Одессы. Хотите отдохнуть от суеты всей семьей или большой компанией? Этот выбор для вас!	\N
321	16	название описания	rehghmdf str.12	123	10	41	t	f	t	описание названия весьма глистовыводящие булочки с плейлистом из жестяных труб	\N
6874	23	london	dfnoiuy str.8	32	4	12	f	f	f	some description	\N
23000	1	Красная однушка на побережье	sdverbt str.43	56	4	4	t	t	f	Невероятно красивая однокомнатная квартира с великолепным видом на море. Имеет красные фасады кухни, в связи с чем и была так названа.	Роскошная квартира с видом на море, расположена в новострое в самом сердце Одессы, в престижном районе Аркадия. Здесь вы найдете все для комфортного проживания: бесплатный Wi-Fi, собственное парковочное место и уютные современные интерьеры. Квартира идеально подходит для отдыха на побережье, ведь до пляжа всего несколько минут пешком. Вблизи расположены лучшие рестораны, ночные клубы и знаменитый Аркадиевский парк. Насладитесь прогулками по Приморскому бульвару, посетите Потемкинскую лестницу и знаменитый Одесский театр оперы и балета.
123	26	в лесу родилась елочка	Пушкина Колотушкина	76	8	1	\N	\N	t	в лесу родилась елочка в лесу она росла зимой и летом стройная зеленая была	\N
45667	17	beautiful apartment from my head qwerty	dfngh str.1	324365787	12345	789	t	f	f	absolutely fucking amazing place to live, u need to try it. Have u tried it? btw u need to try it.	\N
987	21	fvtbrttyn	dbnhmu str.3	1234	1234	1234	t	t	t	absolutely fucking amazing place to live, u need to try it. Have u tried it? btw u need to try it.	\N
4869564	22	beautiful apartment from my head	gnyugfngh str.9	2	34	4	t	t	t	Прекрасная двухкомнатная квартира на девятнадцатом этаже жилкомплекса Гагарин Плаза с видом на море	\N
68763	25	bnytuyutngbvdcasvbyu	entmuyiou str.88	65	45	3457	f	f	t	erndtngbdfvsd	\N
240000	27	Великолепная квартира со всеми удобствами	великолепный адрес	100	8	20	t	t	t	очень краткое описание великолепной квартиры в шикарном районе! Великолепное описания великолепной квартиры в великолепном районе с великолепными великолепностями, так же великолепные апартаменты оснащены великолепным вайфаем и великолепным видом	\N
\.


--
-- Data for Name: images; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.images (id, bytes, content_type, is_preview_image, name, original_file_name, size, apartment_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, active, date_of_created, email, name, password, phone_number, roles, username, role) FROM stdin;
3	\N	2024-12-18 20:54:37.348	bengaminfein@gmail.com	Denys	$2a$10$kLBkS80saQgAGONx7vrUYeSbwIlIEzYlj9P/GobgDNlkDqPiO66Pe	+4915140138999	\N	DenysAdmin	admin
4	\N	2024-12-18 20:58:40.598	example@gmail.com	Denys	$2a$10$7mO.Lhjl0hY63XTWssRsY.COA./CTjcHpNO57P853B3PnkbFO1/q.	+4911111111111	\N	DenysClient	client
5	\N	2025-01-10 20:22:24.488	asdf@gmail.com	mr. Twister	$2a$10$ig0jbtXq/sD2XQnU65Bcie0Ry2WITupSk9On5Gs7IPYmpmElgFAGm	+4909876543211	\N	qwerty	client
\.


--
-- Name: apartment_info_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.apartment_info_id_seq', 27, true);


--
-- Name: images_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.images_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 5, true);


--
-- Name: apartment_info apartment_info_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apartment_info
    ADD CONSTRAINT apartment_info_name_key UNIQUE (name);


--
-- Name: apartment_info apartment_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.apartment_info
    ADD CONSTRAINT apartment_info_pkey PRIMARY KEY (id);


--
-- Name: images images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: images fkjk8p9tp1gv311ry9hohbs0fl9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT fkjk8p9tp1gv311ry9hohbs0fl9 FOREIGN KEY (apartment_id) REFERENCES public.apartment_info(id);


--
-- PostgreSQL database dump complete
--

